name: PetLife
version: '${project.version}'
main: net.phileasfogg3.petlife.PetLife
api-version: '1.21'
authors: [PhileasFogg3]
description: A Minecraft Plugin based on "Third Life" by Grian. Developed by PhileasFogg3 for personal use with friends. Pet Life is based on third life but with a twist, your life is tied to your pet's life and each pet has a unique ability!
website: https://github.com/PhileasFogg3
