name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List tags
        run: git tag

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'  # Java version

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Run Maven build

      - name: Get the latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Bump the version number
        id: bump_version
        run: |
          version="${{ env.latest_tag }}"
          commit_message="${{ github.event.head_commit.message }}"
          last_word=$(echo $commit_message | awk '{print $NF}')

          if [[ "$last_word" == "RELEASE" ]]; then
            # Increment major version and reset minor and patch
            major=$(echo $version | cut -d. -f1 | cut -dv -f2)
            new_major=$((major + 1))
            new_version="v$new_major.0.0"
          else
            # Normal version bump logic
            major=$(echo $version | cut -d. -f1 | cut -dv -f2)
            minor=$(echo $version | cut -d. -f2)
            patch=$(echo $version | cut -d. -f3)
            new_version="v$major.$minor.$((patch + 1))"
          fi

          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Set up git user info
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Set release name and pre-release flag
        id: set_release_name
        run: |
          last_word=$(echo "${{ github.event.head_commit.message }}" | awk '{print $NF}')
          if [[ "$last_word" == "RELEASE" ]]; then
            release_name="$last_word ${{ env.new_version }}"
            is_pre_release="false"
          elif [[ "$last_word" == "SNAPSHOT" || "$last_word" == "PRE-RELEASE" ]]; then
            release_name="$last_word ${{ env.new_version }}"
            is_pre_release="true"
          else
            release_name="Release ${{ env.new_version }}"
            is_pre_release="false"
          fi
          echo "release_name=$release_name" >> $GITHUB_ENV
          echo "is_pre_release=$is_pre_release" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}  # Use the dynamically set tag name
          name: ${{ env.release_name }}  # Use the dynamically set release name
          body: ${{ github.event.head_commit.message }}
          files: target/*.jar  # Include JAR in the release
          pre_release: ${{ fromJson(env.is_pre_release) }}  # Convert string to boolean
